Update v7-migration.md
`--compilers` [is deprecated](https://github.com/mochajs/mocha/wiki/compilers-deprecation).
And the `js:` must go. Otherwise you get a `Error: Cannot find module 'js:@babel/register'`, verified with `mocha.opts` and command line.
Without `js:` it works.